sudo: required
env:
  global: 
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    language: generic
    before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
    - tar -xzvf protobuf-cpp-3.6.1.tar.gz
    - pushd protobuf-3.6.1 && ./configure --disable-shared && make && sudo make install
      && popd
    script: "./ci/travis.sh"
  - os: osx
    osx_image: xcode9.4
    language: generic
    env:
    - HOMEBREW_TEMP="/tmp"
    - LDFLAGS="/usr/local/lib/libprotobuf.a /usr/local/lib/libprotoc.a"
    before_install:
    - brew update
    - EDITOR="sed -i '' 's/system \".\/configure\",/system \".\/configure\", \"--disable-shared\",/g'"
      brew edit protobuf
    - brew install protobuf
    script: "./ci/travis.sh"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2"
bintrayUser:
  secure: aYYlcs5m36yblX6pJWmyQsnsX353zxPCZo/rtumn0twelAL7aOIhX3KL4HUPmrzsKnfV1/gzTCblnrRsQlTueTS6gG0s34aVhwr98hzgi1y2NjMp3gQgB8XfQ/T9Wy7Iw8cBt/iU2hARK3HRuJzrs6PnmIXmI5jb9Po1pLpaqtAcSRPmxgSL1T5XP2XSe+J2KnzgqDRPZEyORXQlOo0VWnJKQH06JmTsu/Fy07maaW1OYd/bf6vqlFofULRvATAiO34jyvQ451JuxG4/p67YLbAyfRZAGAbDcW+bgdRM3iU9+dH3gTvI7jJcy5AwsQDMtVYdWlkeB2gAezbsY+HZ2Blre76IEHTCOUL4slfrqP0kMzY6RD346E7zEUdFFX9L0WXwS1MYsA+eHhHcgy2AIFPSBTod6lBWT+9wntSKawgSmuczAv6TNmcA+7KzeRhMXeL7I4JdpzKWk/nkr/nsB8IQrVbZmuFRkMu7rKpk7iafnh69lkeyZX2wa5T6mEhTchCPTe3izM6Sndmja9xU8ZgGj3OUejBl/yBWZWCnL5HvkzWJL6/0m9fWDpVn/kkY+iG7ZGB5M6BFSOrWJXjt6jy6ECyfXn5/ir1lwVh2Gn+6u5GiZ5Hi0j6VwUTz1xjFPkDIlUOwviY/W11xXOK+YcemKt4eLE10kQxcgll4a44=
bintrayKey:
  secure: jQqHpSesoAGR8cNlsOAIisvbqAicvqNP+NbvCEvHxLhuOhUMiD3jt0y390fU9bNTcDiBpX6my4QGR00psH3kJfbkqyJTxQFpP+gH84AzOXjHXTY+3E8ygqAhKvbT2LZn8amceMx47eZrrFltk1p0kC7N+RtUk7tvLEfK7INpADEdSIC/OggYUs8eCHCZZEBnpe2vzK0KdPDob02F18e7ne2rx93Y5qM58M+STcEtQN8AmBQmkxKPInqn+Kxc7WFFAtYFGCjFgnuqGliZunb67sq+foWiVE3x/uqFLwNMPFqwPaYujhRTN0MoDTl+mogkU57c3slXpQ2nAgO9ifiDeofQolZpMyvajeGEdcmp1D/Jg85M6wMWg4DQY+INRxRloX/frj9Jk+S3d3aAKc+mbBmW75ufqqVb3UMsEgA7ZOVJwST0KHVyWo70B1KqSSoyL3CdiiPv73Hr+hQrOHDS80LOfoeYr6fBd0eC70V/LhjEooXC6/8UsNaQ06bP7e3Olf4epzpX1JfEVLmRWUOevEcHGT04GgNqXKFZKG3C64dLfEVG3vfAJkD0BN3YAfL4AN8NBYW25NMd+VZHL3K6qPGz7Ycq/U0CxXV+RdJWgt2s5xJrU+ILcR9VqJcz2W5WmfeIenkFqwz5KLVCfy73oes8lnMCDFCQVxD0yRqipOE=
