sudo: required
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    language: generic
    before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
    - tar -xzvf protobuf-cpp-3.6.1.tar.gz
    - pushd protobuf-3.6.1 && ./configure --disable-shared && make && sudo make install
      && popd
    script: "./ci/travis.sh"
  - os: osx
    osx_image: xcode9.4
    language: generic
    env:
    - HOMEBREW_TEMP="/tmp"
    - LDFLAGS="/usr/local/lib/libprotobuf.a /usr/local/lib/libprotoc.a"
    before_install:
    - brew update
    - EDITOR="sed -i '' 's/system \".\/configure\",/system \".\/configure\", \"--disable-shared\",/g'"
      brew edit protobuf
    - brew install protobuf
    script: "./ci/travis.sh"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2"
env:
  global:
  - secure: "z+gA4stWCnacsqoGmzUaLKIS0xehdMfjcwzX063D5MDo0RhKBeKHrIhEQt0Vhj8NgV2Ay03jCZA8uatBLdWkD5vBkYu/6IpoUa5+1RZFHyiFm0KKlrjx+0dfZacTwIaBgyiNOLN2hcSz0JqZYAXdSn/l0PaZicYdndbXrOE1f8c3AWIbMQBuyRgH3CSf7TocSYLo6esP/tXL2fX1E5SdzHFOPAF3uQ03SQHt8yIE0jCYp3/AxTibLZCQYqGNzq2EE2HcyoGZfE7ai71WLgeohZiSJgM48B22bSpPPOAZkZk1l78x5Vrcgoc6otdDDv13UOZk49LFtkRE5vUzbRYV56D9MufQcsOqYSZxnAyiP2pPUnUUl/HXUtWC9oe81E+gzDvq83sF/MK53FHj/Gy4spvLZLASUeJXt+z382PFmm60boIFJCQAN3gCkkfE5wI1WQhNR4O8u3GBzx8BPia6K9lW04w9KAyzVY7ZiboDhNPClC05u5hrK8XAwCGyQhzEsjZUve3KTeW6rgGbngsfSUZ5wRAuX5A3tnYy7x3HCW2CDcdWD09kMFN57F446QWNulRIu6yGxuoCoXzTlUSSYvbRGGyboyo9f5hVJ2kljWGDzXmgdsI8TeABK+7XDKmRhbWDiDYK/JHIimmM2pYllzLS5HUy/OnFRl5aDuT9nsA="
  - secure: "NA4u72hakEy6sHQQZPxkTjk5ZQVQsHokOmEcultHdfODgaPQUXo+corT27mG9B9FtKJ9e0AUUl+8zj7OTPGobMmmdxAkbNL9k/2LxPK7DdtjUgFa9+/Kg6QMB9O59RY3bVNLe35AtJHwRxeRbhYmY8fKAIPYnwSxM3XJMSCWk3GdaA3S96mWCQLypACqCWZzKyLVyf0yijYCKRGSOHqCqg/cqKBSpKOIm5xT8OGO3pXe9MYuHTXNifeJ8+JBq8UqG3q0yr3PGumqfkqIdQgy1wNBooPj1YDO7l39Rb77RINb8MseuGNBpKZHlgrV2zKHmJFROiVwjtSzlqbTITQxqH6il7S2A2bN5Taxbaynx9BWWIdErLwVmXJvdlfTtGU29gNrpvtBF7wL8mc3/nnmnffLbus69NUSIgU3XoPpc4PDKtn8nx9MnU1e9m/DNbuilc4IO2+F4yBQzX8k8ruR49272GZxMG1XAmuIT3R+/JvBXGdRfjXGGQt/NH+JmYqUb+gZP5rC5e2G38Cyh/x4vi4spSTE+FVu6CC7EOQG4N8O+q7MaxAZJUGpsthzQZLQ9bHFrqHDm1tItj4Tbgu0WI0fOnTF7IqMKNCnbkOEvKawsy9NTBzj1bWMn3uhANexsBailJbOK0qyxTRVdBJUhyKjEJqzycQ+oQoeEtQ0WJs="
